global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway-metrics
    metrics_path: /metrics
    static_configs:
      - targets:
          - api-gateway:8080

  - job_name: scholarship-health
    metrics_path: /health
    static_configs:
      - targets:
          - scholarship-service:3000

  - job_name: socioeconomic-health
    metrics_path: /health
    static_configs:
      - targets:
          - socioeconomic-form-service:3001

  - job_name: psychological-health
    metrics_path: /health
    static_configs:
      - targets:
          - psychological-care-service:3002
